### ISSUE TITLE
Cannot use Remote Desktop with localhost and a specific port

### ISSUE THREAD

**Issue by didierfolly** [BornToBeRoot/NETworkManager#1214]
**Describe your issue**:
When I use the feature "Remote Desktop" with the address localhost:portXYZ the application crashes and closes.
Information: I can access the same VM and port on VirtualBox with the standard "Remote Desktop" app from Windows works.

**Steps to reproduce the issue**:

1. Start a VM with VirtualBox which has a forward port XYZ redirected to the VM host port 3389 (Remote Desktop)
2. Open "NetworkManager" app
3. Run a "Remote Desktop" with the host: localhost:portXYZ (ex: localhost:52000)

![2021-07-27 19_27_37-NETworkManager 2021 6 26 0](https://user-images.githubusercontent.com/13508431/127200203-6fbf1eb9-a598-4bb9-afe6-be97c4f18c42.png)

**NETworkManager version**: 
2021.6.26.0

**Windows version**:
21H1 (OS Build 19043.1110)

**.NET-Framework version**:
5.0.302

**Screenshots**
See image above.

<details>
<summary>Eventlog (if application crashes)</summary>
Faulting application name: NETworkManager.exe, version: 2021.6.26.0, time stamp: 0x60513887
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1110, time stamp: 0x4809adf2
Exception code: 0xe0434352
Fault offset: 0x0000000000034ed9
Faulting process id: 0x296c
Faulting application start time: 0x01d7830b6c1544c1
Faulting application path: C:\Program Files\NETworkManager\NETworkManager.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 69380251-44a3-4b03-921e-df3ef4ec9dba
Faulting package full name: 
Faulting package-relative application ID: 
</details>

**Comment by BornToBeRoot** [comment]
Hi @didierfolly,

is there a second entry in the event log with the crash report / stacktrace?

I will try to reproduce and fix it.

Greetings

**Comment by BornToBeRoot** [comment]
@didierfolly found the problem (and some other issues with remote desktop settings 😄 ). 

I will fix this for the next version.

I would recommend to use a fixed screen size, because the reconnection when the screen size changes does not work properly...


![image](https://user-images.githubusercontent.com/16019165/128592267-a83526f2-11ec-4c63-a7d6-8a724e917f27.png)


![image](https://user-images.githubusercontent.com/16019165/128592381-0d7574f5-a35f-4077-aa37-4b4cbc222191.png)
