### ISSUE TITLE
Remote Desktop - Add Deffault credential (Login and Passsword)

### ISSUE THREAD

**Issue by alexeysorok** [BornToBeRoot/NETworkManager#1222]
**Ability to set a default login and password for RDP connections**:
It is very necessary to add the ability to add accounts by default when connecting via the RDP protocol, so that you do not have to constantly drive in your login and password when creating a new connection.
So that the login and password are substituted by default, which will be set for the group or for the entire profile in general. 
For example, how is it done here 
![image](https://user-images.githubusercontent.com/41438642/129030120-e17c390e-9e45-4780-b7ee-fffd15cb9d46.png)

**Comment by BornToBeRoot** [comment]
Hi @alexeysorok,

i think the feature makes sense and i wanted to implement it for a while now. Also for other settings like SSH-Keys.

I will add groups to the profiles (because this file can be encrypted with a master password). This will break the existing profiles, because it was never designed for that.

- Every profile has 1 parent group
- Every group can have n profiles
- Group in group is not possible

Here is a PoC PR: #1236 

I need to fix some bugs, build the ui and implement the logic for remote desktop.

**Comment by BornToBeRoot** [comment]
@alexeysorok Hi, i implemented the feature. Will be available in the next release!
