### ISSUE TITLE
Request for most-recently used in Wake on Lan

### ISSUE THREAD

**Issue by webprofusion-chrisc** [BornToBeRoot/NETworkManager#1270]
While trying to use the Wake on Lan feature I've struggled to find a way to actually wake a device if I only know the IP (not the mac). I can obviously wake the machine up and look at the arp table to see what the mac address is, but that kind of defeats the purpose.

Could a most-recently-used (or saved hosts) feature be implemented so you can choose from known machines, even when they are asleep? I see there is 'Add Profile' but you have to know the details of the machine, while the details of the machine are blocked by the UI, so you can't see what the details of the machine are :) the whole window also cannot be dragged out the way when the data entry UI is open, which blocks getting to other info (like a command window).

**Comment by BornToBeRoot** [comment]
Hi @webprofusion-chrisc 

this is what the profiles are for. The devices can be stored in a profile and used across the tools.

You can copy the MAC address from the ARP table or from the IP scanner and then paste it into the profile. In the IP scanner you have to enable  `Resolve MAC address and vendor`  to get the MAC address. ARP does only work in the same subnet, because it's layer 2. Also the Wake on LAN will only work in the same subnet because this is a broadcast package.

![image](https://user-images.githubusercontent.com/16019165/136229731-6e5ee925-4a76-4a4c-8ee6-d22d69319f8f.png)

You can also create a profile directly from the ip scanner result. But currently the mac address is not passed to the dialog. **I can change this in a future release to make it easier to create a profile. Also to pass other values like a url.**

![image](https://user-images.githubusercontent.com/16019165/136229230-b84c90ef-868f-4ad9-b148-94d6ea6bf776.png)

I don't know if it makes sense to have a history (maybe a dropdown in the mac address textbox) in the wake on lan, when you can use the profiles for this.


The dialog is currently integrated in the main window and can't be dragged out. This would require a lot of code changes.

Greetings
BornToBeRoot

**Comment by webprofusion-chrisc** [comment]
Thanks! I think part of the reason I didn't persevere with the profiles part is I couldn't get it to save - the Save button remains grayed out presumably because I'm failing some sort of validation (values are a random example):

![image](https://user-images.githubusercontent.com/2445502/136314187-131339e0-fdf7-4011-8ed0-e114a3c6ab84.png)

**Comment by BornToBeRoot** [comment]
Can you check if the general tab is correct:

![image](https://user-images.githubusercontent.com/16019165/136358243-579cb31c-2f7b-4a27-b3db-8b149c0ae193.png)

Name, Host and Group are required. An the host doesn't allow a space
