### ISSUE TITLE
Dutch translations incomplete, or sometimes not quite correct 

### ISSUE THREAD

**Issue by PjotrB** [BornToBeRoot/NETworkManager#1271]
Various screens show a mix between Dutch and English.
I have made some screenshots, highlighting English texts for which there seem to be no translations - see below.

**NETworkManager version**: 
2021.9.5.0 = latest release at this moment

**Windows version**:
10 Pro, build 19041.1237

**Screenshots**

---

Splash screen at start:
![image](https://user-images.githubusercontent.com/1635838/136168171-ccdcc54f-4031-45a9-bb3d-5f931c84396f.png)
Incorrect -> text "On" is translated as "Op", but here it should be "Aan".
The rest is missing.

---

Network interface tab, "Information" panel:
![image](https://user-images.githubusercontent.com/1635838/136168690-90d58178-e824-475a-8b05-4f80404a9a3c.png)
Incorrect -> text "Empty DNS-cache" is translated as "Lege DNS-cache", but it should be "DNS-cache legen".
The rest is missing.
It wouldn't make sense to translate the very technical terms like "DHCP lease", but the words around it should be translated.

---

Network interface tab, "Bandwidth" panel:
![image](https://user-images.githubusercontent.com/1635838/136169406-dd0f67b5-4054-4c43-a962-9e333b3aefc1.png)
6 missing translations.

**Comment by BornToBeRoot** [comment]
Hello @PjotrB,

the translation is created by the community. You are welcome to help on Transifex to improve it. Even if the language is 100% translated (on transifex), it may be that only the English strings were taken over here (partly due to a bug in the sync between transifex and github some time ago).

![image](https://user-images.githubusercontent.com/16019165/136226904-5a42454e-f1f8-47d3-bd22-726989ca02ea.png)

If no translated string is available, the english one is automatically displayed as fallback.

Here is the project on transifex. You can join with your github account.
https://www.transifex.com/BornToBeRoot/NETworkManager/

The translation is updated on every release.

Greetings
BornTobeRoot
