### ISSUE TITLE
Window title update based on active tab

### ISSUE THREAD

**Issue by VelliusG** [BornToBeRoot/NETworkManager#1437]
### Discussed in https://github.com/BornToBeRoot/NETworkManager/discussions/1436

<div type='discussions-op-text'>

<sup>Originally posted by **VelliusG** May 10, 2022</sup>
Have the application update the window title to reflect which tabs are selected.

Ex:
NETworkManager - Remote Control - PROFILENAME
NETworkManager - Web Console - PROFILENAME
NETworkManager - Web Console - PROFILENAME - URL

This would allow someone to use Auto-Type features from KeePass to input credentials based on current tabs selected in the application.</div>

**Comment by BornToBeRoot** [comment]
The title could become very long. When the tab is dragged out, i already do this like "NETworkManager VERSION - Web Console"

If you just want Auto-Type from KeePass you can use `* - PuTTY` in target windows because putty is embedded as process. 
For Remote Desktop there is a separat window, something like "Enter Windows Credentials".
It would make sense for the Web Console and maybe SNMP.

i don't have much time at the moment, but i'll take a look at it sometime.

**Comment by BornToBeRoot** [comment]
I think the title will then just too long and better use the window bar (buttons, profiles, etc.).

If someone wants to implement this - feel free to send a pull request.
