### ISSUE TITLE
Traceroute skips hosts.

### ISSUE THREAD

**Issue by MichaKersloot** [BornToBeRoot/NETworkManager#1523]
Traceroute only shows first 3 hosts and the end host and skips hosts/routers inbetween.

**Steps to reproduce the issue**:

1. www.google.com in trace
2.
3.

**NETworkManager version**: 
2022.8.18.0

**Windows version**:
Windows 11 22000.856

**Screenshots**
![image](https://user-images.githubusercontent.com/3512195/187718482-bf20b94b-5271-47d4-bbcb-90000bdd5f45.png)

![image](https://user-images.githubusercontent.com/3512195/187718604-295ece02-a20a-4c11-b762-e39f0aab4417.png)

**Comment by BornToBeRoot** [comment]
Hi @MichaKersloot,

thanks for reporting this bug. It looks like the bug has been there since the migration to .NET 5/6. 
If there is a timeout, the destination ip is returned and my function things it's complete...

The Ping class behaves differently in .NET 6 than it does under .NET Framework.... Looks like microsoft has changed something here.

Also PowerShell behaves differently in 5.1 than in 7.2:
```
$ping = [System.Net.NetworkInformation.Ping]::new()
$pingOpt = [System.Net.NetworkInformation.PingOptions]::new()
$pingOpt.DontFragment = $true
# Change to the hop that timedout
$pingOpt.Ttl = 8
# GitHub IP
$reply = $ping.Send("140.82.121.4", 1000, 32, $pingOpt)
Write-Host "IP: $($reply.Address)"
```

___

Possible workaround:

- Check Status `TimedOut` & continue

There is a new issue, when you can't ping the destination. But this issue also exists in tracert:

![image](https://user-images.githubusercontent.com/16019165/189459191-627e7dac-e1e2-4e33-90b6-0d9d73b9fe30.png)
