### ISSUE TITLE
Allow multiple IPv4 addresses for interface at profile creation

### ISSUE THREAD

**Issue by adremides** [BornToBeRoot/NETworkManager#157]
Information shows all the addresses of the interface but profile creation allow to add only one address.

**Comment by BornToBeRoot** [comment]
This is possible with a netsh command. If you want, you can send me a pull request. I am currently working on some other features.

Command: `netsh interface ipv4 add address`

**Comment by BornToBeRoot** [comment]
I don't want to add it to the profile because this makes everything more complex and i don't think this is a function that is used frequently.

This function should make it possible to switch quickly between networks (mangement network, server network, etc.)

Since some servers occasionally need to have ip addresses added (e.g. web servers) and because netsh is not "easy" to use, it's now possible to add and remove ip addresses from the config view.

**Comment by BornToBeRoot** [comment]
![image](https://user-images.githubusercontent.com/16019165/119051725-d21fe900-b9c3-11eb-8b20-bddd40a17071.png)
