### ISSUE TITLE
No hostnames on Windows 10

### ISSUE THREAD

**Issue by PonchoPowers** [BornToBeRoot/NETworkManager#159]
I'm not getting any hostnames on Windows 10.

I am using a DrayTek router.

**Steps to reproduce the issue**:

1. Open NETwork Manager
2. Set the IP range 192.168.1.0/24
3. Click scan

**NETworkManager version**:
1.8.1.0

**Windows version**:
Windows 10

**.NET-Framework version**:
4.6

**Screenshots**
![image](https://user-images.githubusercontent.com/7858744/49701156-85276e00-fbe0-11e8-90e6-2e5a241a0cd6.png)

**Comment by BornToBeRoot** [comment]
Does your dns server resolves the hostname?

`nslookup 192.168.1.1`

**Comment by PonchoPowers** [comment]
C:\Users\MatthewB>nslookup 192.168.1.1
Server:  cache03.dns.zen.net.uk
Address:  212.23.6.100

*** cache03.dns.zen.net.uk can't find 192.168.1.1: Non-existent domain

C:\Users\MatthewB>

**Comment by PonchoPowers** [comment]
I presume this is because my router does not have a hostname?

**Comment by BornToBeRoot** [comment]
Your PC is using a public DNS server (212.23.6.100). This server would never resolve any local addresses.

You should change your DNS server to something local (in normal home networks, your dns server is the router). This settings can be configured in windows (network card) or via DHCP in your router settings.

Since this is a faulty configuration of your system and not a problem of NETworkManager, I will close the issue.
