### ISSUE TITLE
Portable Version

### ISSUE THREAD

**Issue by smaragdus** [BornToBeRoot/NETworkManager#163]
_NETworkManager_ version [1.8.3.0](https://github.com/BornToBeRoot/NETworkManager/releases/tag/v1.8.3.0) (portable);
_.NET Framework 4.6.2_;
_Windows 8 x64_;

The portable version really saves configuration in 'Settings.xml' file in 'Settings' sub-folder inside program folder. But 'user.config' is saved in AppData:

`C:\Users\User\AppData\Local\NETworkManager\NETworkManager.exe_Url_xstoycfmdd4mjoqectd3tds3ss2bdhfi\1.8.3.0\user.config`

I believe that a truly portable version should not write outside its program folder. What about saving 'user.config' file next to 'Settings.xml' file in 'Settings' sub-folder? This will make the portable version fully portable.

**Off-topic**
The program is very capable, I like it although I am not a fan of flat, modern interfaces. Thanks for your good work. Happy holidays.

**Comment by BornToBeRoot** [comment]
There are a few settings saved in `%localappdata%`, but these are machine specific.

Only the two things are store there:

1) Window position (size and position of the window), which comes from the MahApps.Metro libary i use.
2) Path to the custom settings location (if you want to store your settings/profiles/credentials in another location... e.g. network share)

The first thing is impossible to change, because it comes from the libary... I would have to implement the feature myself. And if you run the program on other machines (e.g. notebook) with a multi/single montitor setup, the window position might be wrong.

I think the settings location is also machine specific, because you must be able to access it. (network drive). Also the non-portable version use this setting, because i need a location with write access to store the settings location.

Everything else (settings, profiles, credentials) is in the settings folder.


Have you any idea how to improve that? (Pull requests are welcome)

**Comment by smaragdus** [comment]
@BornToBeRoot 

Thanks for the detailed explanation, I understand your point. I am not a programmer, I just supposed that the parameters for program window geometry could be saved in program folder too (I have seen this in other .NET programs).

Please feel free to close this issue, I am not closing it myself because you might have some other considerations.
