### ISSUE TITLE
how to add tightvnc2.8.11 into your project

### ISSUE THREAD

**Issue by HelloJango** [BornToBeRoot/NETworkManager#167]
**Describe your issue or feature request**:

**Steps to reproduce the issue**:

1.How can I add Tightvnc2.8.11 into your project,then I can connect to others,and others can connect to me（add TightVNC Viewer and TightVNC Server）

2.there is a error (warning:算法运算导致溢出)

3.how to compile your project(vs2015?)

**NETworkManager version**:

**Windows version**:

**.NET-Framework version**:

**Screenshots**

<details>
<summary>Eventlog (if application crashes)</summary>

</details>

**Comment by BornToBeRoot** [comment]
Hi,

1) You must install TightVNC (Viewer) on your system.

Then you can add the `tvnviewer.exe` in the settings.

![image](https://user-images.githubusercontent.com/16019165/51753295-b2a97780-20b9-11e9-8db5-4a01c838372a.png)

Then you can use profiles to connect to the systems (like the RD/PuTTY feature).

![image](https://user-images.githubusercontent.com/16019165/51753350-cfde4600-20b9-11e9-86bd-2bec810425d2.png)

You can't use TightVNC Server with my tool... If you want to connect to your system via VNC, you have to install and configure it.

2) Never saw this error, can you send a screenshot? When does the error occur?

3) I use VS2017 Community... You must download the whole source and then open the /Source/NETworkManager.sln in VS.

**Comment by HelloJango** [comment]
![error](https://user-images.githubusercontent.com/46467364/51813351-c4c12b00-22f0-11e9-8a71-671521810d66.png)

**Comment by HelloJango** [comment]
Can you modify the UI of TightVNC with C#?Tightvnc's original interface is low

**Comment by HelloJango** [comment]
![default](https://user-images.githubusercontent.com/46467364/51813507-ac9ddb80-22f1-11e9-9d06-1e0abe49bfb8.png)
Is the input of this login interface implemented by yourself?Tightvnc（2.8.11） has its own implementation with MFC

**Comment by BornToBeRoot** [comment]
@HelloJango 
1) TightVNC has a .NET SDK, but it's not open source/free.

2) Modifying the TightVNC UI is not possible.

3) The error in your screenshot occurs from time to time. It happens when i try to remove the border from the original window. (This works without issues in PuTTY/PowerShell) https://github.com/BornToBeRoot/NETworkManager/blob/3d911ebb77a93afce0b5fbb8df5e8b0570ef65f7/Source/NETworkManager/Controls/TightVNCControl.xaml.cs#L169
I haven't found a workaround yet. 

4) I currently try to replace TightVNC with TigerVNC. It is a fork and looks more maintained... Also the vncviewer.exe has a modern interface.

**Comment by BornToBeRoot** [comment]
Closed #175
