### ISSUE TITLE
Configure Gateway for Remote Desktop

### ISSUE THREAD

**Issue by rkl110** [BornToBeRoot/NETworkManager#1913]
It would be awesome to configure a gateway server for RDP Sessions.

**Comment by BornToBeRoot** [comment]
Do you mean this option?

![image](https://user-images.githubusercontent.com/16019165/219079715-007f80f0-4343-40ba-a976-0573ff30bcdc.png)

I need to check the library if it's possible.

**Comment by rkl110** [comment]
Yes, thats the option I'm missing

**Comment by BornToBeRoot** [comment]
Should be possible. Can be set via `RdpClient.TransportSettings4.*` 

https://learn.microsoft.com/en-us/windows/win32/termserv/imsrdpclienttransportsettings
https://learn.microsoft.com/en-us/windows/win32/termserv/imsrdpclienttransportsettings2
https://learn.microsoft.com/en-us/windows/win32/termserv/imsrdpclienttransportsettings3
https://learn.microsoft.com/en-us/windows/win32/termserv/imsrdpclienttransportsettings4

But i need some time to implement and test it... i have to fix some other bugs first.

**Comment by BornToBeRoot** [comment]
Hi @rkl110,

i have implemented the Gateway server in the global settings. Can you test it - because i currently don't have a gw server 😄 ?

![image](https://user-images.githubusercontent.com/16019165/227753444-dce734b2-4efa-473f-8631-d0061f03997b.png)

If this works, I also add it to the group/host profiles. Since the profile file can be encrypted, I also add username/domain/password support there.

Download: https://github.com/BornToBeRoot/NETworkManager/releases/tag/2023.3.26.0

**Comment by rkl110** [comment]
Hi @BornToBeRoot,

thank you verry much for implementation. I just test it an I can login via Gateway Server. 
But I think there are still some bugs. I had to pre safe my credentials and the resolutions stayed low.

But it might be that those are layer 8 mistakes.

Kinde Regards

**Comment by BornToBeRoot** [comment]
Thanks for the feedback.

The display resolution should work the same as before. But i can check the code if there is something wrong.

I will add credentials for the gateway in the group / host profile. If nothing is set, i think it will use the credentials from the rdp client, but i am not sure -.- the documentation from microsoft for this lib is a nightmare.
I will implement it and give you an update here :)
