### ISSUE TITLE
Selectable Interface on all tools?

### ISSUE THREAD

**Issue by mem16421** [BornToBeRoot/NETworkManager#2151]
I have been trying this tool out when troubleshooting at different network sites.  My laptop has a VPN TAP, WiFi, Built-in Eth, and USB Eth interfaces.  When using the different tools, like IP Scan as an example it defaults to my VPN Interface.  So if I try to scan a network that I am plugged into using my USB Eth Interface it finds nothing.  Others like port scan, traffic, etc seem to do the same.  Can there be a way to select which interface you want to use, or even a setting for the default interface?

**Comment by BornToBeRoot** [comment]
Hi @mem16421,

I'm not sure if I understood this correctly, so please correct me if I'm wrong.

In the IP scanner, do you mean the detection of the current network (via this button)?
![image](https://user-images.githubusercontent.com/16019165/233495969-cafa1d78-7be3-4c51-8568-ebb09eb3796f.png)

If yes, you can scan the network of an adapter also from the interface view:
![image](https://user-images.githubusercontent.com/16019165/233496232-54a3552f-5a74-4034-bfcf-35b208d43115.png)

---

For the other tools like ping, port scanner, traceroute... this sounds more like a routing "issue" (default behaviour of Windows - or any system).

For example... if you have 2 interfaces (LAN `10.0.0.0/24` & WiFi `10.0.1.0/24`) - and both have internet access:
1) You should be able to connect to (ping, traceroute, port scan, etc.) hosts in each network, because your computer knows which route (adapter) to choose.
2) If you want to connect to a host in the internet (like 1.1.1.1), Windows will choose the route with the lowest metric. Normally this should be the LAN interface. You can verify this with traceroute.
3) If you now use a VPN - depending on the configuration - all traffic goes through the VPN. If you use split-tunneling, only your internet traffic **or** selected networks go through the VPN.

If you want to modify the routing table, you can use  `netsh`. I plan to implement a feature to show & modify the routing table (ref #1860)
