### ISSUE TITLE
Port Scanner - odd results

### ISSUE THREAD

**Issue by PCAssistSoftware** [BornToBeRoot/NETworkManager#242]
Hi

Getting odd results from Port Scanner, scanning my whole network of 192.168.1.1 - 192.168.1.254 for ports 1-80 as a test and getting odd results.

Basically it is showing ports like 25 being open for IP addresses which don't even exist on my network (home)

See screenshots showing some of the results for one address, and also showing my connected devices on my router where that address is not used, and I can't ping it either

So why is it finding open ports for something which doesn't even exist??

Any thoughts or tests I can do please?

![image](https://user-images.githubusercontent.com/10872799/71769632-8b8b3500-2f1b-11ea-8b44-34c8369f08e8.png)

**Comment by PCAssistSoftware** [comment]
Another example image below - scanning for port 25 on whole range - says it is open on all IP addresses - when only 8 devices on network!!

![image](https://user-images.githubusercontent.com/10872799/71768364-419b5280-2f0d-11ea-8276-5d366291ca4c.png)

**Comment by BornToBeRoot** [comment]
Can you try to connect via telnet.

**Comment by PCAssistSoftware** [comment]
It is only certain ports it seems to be showing wrongly e.g. if I do port 80 instead, then it only finds it open on 5 devices which would be correct

**Comment by BornToBeRoot** [comment]
And can you try this from another pc in your network

**Comment by PCAssistSoftware** [comment]
C:\Users\darre>telnet 192.168.1.249
Connecting To 192.168.1.249...Could not open connection to the host, on port 23: Connect failed

**Comment by PCAssistSoftware** [comment]
> And can you try this from another pc in your network

And now I am totally confused as from another PC on same network it works as it should, but the one with issue is my main PC with proper antivirus/firewall etc running, so no reason it should be finding things differently

Any thoughts please?

**Comment by BornToBeRoot** [comment]
Maybe something is listening for this traffic on your pc (maybe antivirus?). You could try netstat, to find more informations... 

25, 110, 465 are mail ports...

The port scanner just tries to open a TCP connection (ip, port). If this don't fail, the result is "open". UDP is not scanned.

**Comment by PCAssistSoftware** [comment]
netstat yielding no clues

AVG Internet Security seems to be the culprit, as when disabled I then get correct results with Port Scanner, but odd thing is I have other machines with AVG Internet Security on and they work fine with it enabled.  So something odd going on with my main build machine

**Comment by PCAssistSoftware** [comment]
The odd thing is that running a variety of other tools and powershell scripts on same computer - they all show correct results e.g. port 25 is open on 6 out of the 7 devices currently on my network

Running IP Scanner in your tool show 7 devices connected

So still confused as to why Port Scanner seems to provide results for devices other than those 7 on network

**Comment by PCAssistSoftware** [comment]
Further to this in relation to the IP Scanner, it finds 7 devices, but looking on my router I have 9 connected.

IP scanner is not showing 2, but I can ping and do nslookup on those two fine from my PC, so why would it not be showing them?

![image](https://user-images.githubusercontent.com/10872799/71769612-5a126980-2f1b-11ea-8e3b-0e52af098b06.png)

Hope you don't mind the questions!   I love the tool, but just need to make sure it is accurate for what it shows me etc

**Comment by BornToBeRoot** [comment]
The IP scanner uses ICMP (Ping) to test whether a device is online. If a device does not respond to ICMP, it will not be shown in the IP scanner.

Your router can see the traffic (or ARP) from this device.

**Comment by PCAssistSoftware** [comment]
IP SCANNER: But with the above example I CAN ping the two devices not shown, hence the confusion

PORT SCANNER: still confused why I can use other tools or powershell scripts and it only shows open ports for machines which actually EXIST, whereas I get a long list of those with e.g. port 25 open when the IP address concerned doesn't even exist and can't be pinged - surely something can be done to improve that side?

**Comment by BornToBeRoot** [comment]
**IP Scanner**
With nslookup you resolve the dns entry for the ip address agains your dns server (router?)... that is not a ping to the device! DNS entrys are stored on the dns server and will also resolve even if the client is not online.
When you enable this setting, they will show up with their dns record, but still not as online because they don't respond to icmp:
![image](https://user-images.githubusercontent.com/16019165/71787313-721ae380-3016-11ea-97f7-72bfb9e901cb.png)

You can also try `C:\> ping 192.168.178.x`

**Port Scanner**
This powershell script does the same as the port scanner in the NETworkManager, maybe you can try it: https://github.com/BornToBeRoot/PowerShell_IPv4PortScanner

https://github.com/BornToBeRoot/PowerShell_IPv4PortScanner/blob/6eba58ac19929e0f70413bbd237fa4b74069a458/Scripts/IPv4PortScan.ps1#L176

https://github.com/BornToBeRoot/NETworkManager/blob/4908d85e6f679abd07f64ddd44f636b7ab60e0a2/Source/NETworkManager/Models/Network/PortScanner.cs#L103

**Comment by PCAssistSoftware** [comment]
The two missing items from the list e.g. .70 and .106 respond to me pinging them as I had already said in the previous post - "...but I can ping and..." - hence the confusion

Will try the other bits you mention tomorrow and respond then

**Comment by PCAssistSoftware** [comment]
Okay, just tried the powershell script quickly and results are below

Perhaps an option in the Port Scanner then to exclude those that are not reachable? because if it is not reachable as per result below then how can it know port is open - especially in this case when I have nothing on my network with that IP address!

`WARNING: 192.168.1.220 is not reachable!

Continue
Would you like to continue? (perhaps only ICMP is blocked)
[Y] Yes  [N] No  [?] Help (default is "Y"): y


Port               : 25
Protocol           : tcp
ServiceName        : smtp
ServiceDescription : Simple Mail Transfer
Status             : Open`


Further to above - you can enter any random IP address e.g. 15.15.15.15 and it tells you port is open!! since my network is in range of 192.168.1.x then clearly 15.15.15.15 doesn't exist internally or externally so there is no way port 25 can be open!

`PS C:\Users\darre\Downloads\PowerShell_IPv4PortScanner-master\PowerShell_IPv4PortScanner-master\Scripts> .\IPv4PortScan.ps1 15.15.15.15 -startport 25 -endport 25
WARNING: 15.15.15.15 is not reachable!

Continue
Would you like to continue? (perhaps only ICMP is blocked)
[Y] Yes  [N] No  [?] Help (default is "Y"): y


Port               : 25
Protocol           : tcp
ServiceName        : smtp
ServiceDescription : Simple Mail Transfer
Status             : Open`

**Comment by PCAssistSoftware** [comment]
Just tested IP scanner again with show all results selected, and the two which were missing now obviously show, and the status is "Timed Out", so perhaps you could have a option to show those rather than having to show all as don't really need to see all the "DestinationHostUnreachable" ones

Just a thought

**Comment by BornToBeRoot** [comment]
**IP Scanner**

`Time out` means the client is not reachable via icmp (ping in cmd --> not nslookup). 

Your router can see the traffic / network packets / arp / etc. from the client. Thats why the clients are shown there as online.

If you scan you network from another pc, it's harder to detect if a client is online. Most common is to use icmp, which is enabled in most of the networks. Some clients (firewalls) block icmp requests.

There are other methods to check if a client is online... nmap has a lot of them implemented... Here is a german article: https://www.elektronik-kompendium.de/sites/net/2103041.htm

I plan to improve the detection sometime and created an issue for it: https://github.com/BornToBeRoot/NETworkManager/issues/245

**Port Scanner**

I have no idea why this happens on your pc. Maybe your AV program plays man-in-the-middle since you wrote it would work when you turn it of and also from antoher pc you have no issue with scanning the same clients...
It's also strange that it's only ports for mail (25, 110, 465) and nntp  (119, 563)

Since I can't reproduce the issue and i don't know how to debug it, i can't help here. Sorry.

**Comment by PCAssistSoftware** [comment]
IP Scanner - okay make sense, just hoped to have an option to be able to show those with "Time Out" rather than having to show all e.g. "DestinationHostUnreachable" - I just meant in the options for IP Scanner have two sliders, one to show all and one to show "Time Out" etc.   

Port Scanner - Got it happening here on multiple PC's now, with or without AVG on, so clearly an issue, only similarity is Windows 10 build 1909 and on same network.  Surely must be way to amend code (or advise me how I can) so if it can't actually see (ping/icmp) a IP address then it doesn't show a port as open when it clearly can't be open if it doesn't actually exist....

**Comment by PCAssistSoftware** [comment]
Could you perhaps give me a pointer as to what line of code I could change in the port scanner so it doesn't return results for devices it can't even ping?

**Comment by BornToBeRoot** [comment]
You could test the ip adress before the port scan starts

https://github.com/BornToBeRoot/NETworkManager/blob/4908d85e6f679abd07f64ddd44f636b7ab60e0a2/Source/NETworkManager/Models/Network/PortScanner.cs#L79

**Comment by PCAssistSoftware** [comment]
Okay, i'll take a look, but you know your code better than me.  Personally think it should be an option in the settings page so you can choose to not show results if device can't be contacted, as it shouldn't just assume port is open if it can't even ping / contact via icmp the IP in question.  Basically the same as your powershell script where it asks you to choose Y if you wish to continue.  It should be an option we can all set, as I doubt my PC or a PC with AVG is the only time this will occur, and it is better to not return results saying a port is open if you can't confirm it is open, very misleading if not.

**Comment by PCAssistSoftware** [comment]
Only rough code (I program in VB usually rather than C#), but doing the below in PortScanner.cs so that it checks address responds to ping before checking port state solves the issue:-

line 105 change

```
if (tcpClientConnection.AsyncWaitHandle.WaitOne(Timeout, false))
                                {
                                    try
                                    {
                                        tcpClient.EndConnect(tcpClientConnection);

                                        OnPortScanned(new PortScannedArgs(ipAddress, hostname, port,
                                            PortLookup.Lookup(port)
                                                .FirstOrDefault(x => x.Protocol == PortLookup.Protocol.Tcp),
                                            PortInfo.PortStatus.Open));
                                    }
```

to

```
if (tcpClientConnection.AsyncWaitHandle.WaitOne(Timeout, false))
                                {
                                    try
                                    {
                                        var _ping = new System.Net.NetworkInformation.Ping();
                                        var pingReply = _ping.Send(ipAddress, 4000, new byte[] { (32 - 1) });
                                        if ((pingReply.Status == IPStatus.Success))
                                        {
                                            tcpClient.EndConnect(tcpClientConnection);

                                            OnPortScanned(new PortScannedArgs(ipAddress, hostname, port,
                                                PortLookup.Lookup(port)
                                                    .FirstOrDefault(x => x.Protocol == PortLookup.Protocol.Tcp),
                                                PortInfo.PortStatus.Open));
                                        }
                                    }
```

and add

`using System.Net.NetworkInformation;`

**Comment by BornToBeRoot** [comment]
Sorry, but i will not include an icmp check in the port scanner because i think it doesn't make sense in this feature. 

If you want to add it to your code/version you can add your code at line 79 (before the comment `//Resolve Hostname(PTR)`)
https://github.com/BornToBeRoot/NETworkManager/blob/4908d85e6f679abd07f64ddd44f636b7ab60e0a2/Source/NETworkManager/Models/Network/PortScanner.cs#L79

In your current code, a ping is executed on every port that is scanned... for performance reasons, this should be in the first `parallel.foreach` and not the second.

---

I still think this ports are false positive... that something on your pc or network is responding to this requests. I don't know what but i found an artice which might help debugging this with nmap: https://hackerific.net/2016/03/20/false-positive-tcp-ports/

---

I will leave this issue open for now. Maybe others have simular issues, and they have other informations how to debug this...

**Comment by PCAssistSoftware** [comment]
Okay thanks, will implement it in my version for now until I find cause - thanks for suggestion of better placement in code, very handy

**Comment by BornToBeRoot** [comment]
Close. Cannot reproduce.
