### ISSUE TITLE
Anti Virus detection

### ISSUE THREAD

**Issue by abasitali** [BornToBeRoot/NETworkManager#243]
Dear Team,

I love you application and you are doing great job, I was recommending your application to my friend and upon download checkpoint detected as TROJAN.WIN32.TRX.XXPE1 and also I did scan online https://www.virustotal.com/gui/home/upload gave me some other and McAfee detected some thing but said its safe.

I am not point out to wrong thing as I am still using as it nice app just  wanted to ask why these other antivirus keep detecting some thing in exe file with different different name.

Regards,

Abdul

**Comment by BornToBeRoot** [comment]
Portable: https://www.virustotal.com/gui/file/1a5a16a863425d827e1c58d711c337873c4c44b914d44f3fc27e327043597078/detection
Archiv: https://www.virustotal.com/gui/file/1942ef7b3541782cb83f37ed802e8ff98dd63579f5772d792462eacf82be7e72/detection
Setup: https://www.virustotal.com/gui/file/c615367946a818b4e67632fa99937723b4006385d86f62f52842709dc35cba1f/detection


It seems that they don't like the setup file... maybe because it's not signed or because it has to be started as admin. This is the first version with InnoSetup... I can try to upload it to McAfee so they can check it. 

Which AV is your friend using?

**Edit**
The scan from the setup was 8 days old. I re-scanned the file via virustotal and now only `SecureAge APEX` detect this file...

**Comment by abasitali** [comment]
He had Check Point of Trend Micro which detected and it did during download not even installation.

Just want to get this resolve as false/positive resolve so who ever wanted to try this software and can benefit will not give up on this false reports.

**Comment by BornToBeRoot** [comment]
The problem is that the installer is not signed and it is not downloaded very often. If you are a trend micro customer, you can submit the file for checking.

You can try to download the portable version or the archiv file and deploy it to a folder in C:\Tools\xxx


Edit: I try to submit the file this evening.

**Comment by BornToBeRoot** [comment]
I have just submitted the setup file to TrendMicro and SecureAPlus. It may take 48 hours for an answer to arrive...

Also got a mail from Symantec (i submitted it there directly after the release) that they reclassified it as safe...

**Comment by BornToBeRoot** [comment]
Got reply from SecureAPlus, TrendMicro and Symantec... here is the result:

https://www.virustotal.com/gui/file/c615367946a818b4e67632fa99937723b4006385d86f62f52842709dc35cba1f/detection
