### ISSUE TITLE
create RDP groups and save credentials

### ISSUE THREAD

**Issue by graphik55** [BornToBeRoot/NETworkManager#253]
Hello,

at first I like to say thanks for such a great tool :)

Could you explain how additional groups can be created for RDP?
And is it possible to save custom credentials for each RDP profile?

I wasn't able to find the options for those features.

Kind regards,
graphik

**Comment by nik0chan** [comment]
Hi there, 

On previous versions you could create a profile to sign-in on servers, on this version I have been unable to find this feature, does it has been removed ? 

Regards, 

Nico

**Comment by BornToBeRoot** [comment]
1)
I removed the feature to encrypt/decrpyt credentials in version 2019.12.0: https://github.com/BornToBeRoot/NETworkManager/wiki/Changelog#version-2019120

It was only used in Remote Desktop and i think there are better solutions like KeePass or other password managers with auto type.

Since the default mstsc is used, you could also save the credentials in the windows credential manager.

2)
To create another group, just change the name in the profile:

![image](https://user-images.githubusercontent.com/16019165/72520423-be0d2a00-3859-11ea-8bdf-79ad903f98ae.png)

**Comment by graphik55** [comment]
Thank you for the fast reply.

1. I understand my hope was to get around KeePass or the Windows credential service.
2. Works perfectly :)
