### ISSUE TITLE
Web console issue

### ISSUE THREAD

**Issue by abasitali** [BornToBeRoot/NETworkManager#266]
I loved the new feature you added but this wont even open any I click on new connection type in or copy paste the link. nothing appear after a while a tab open blank screen.

trying to open ESxi Vcenter SSL is untrusted. my default browser is Brave browser.

Do i need to set Edge or Chrome to be default or some thing ?

Also even trying to open printer example http://0.0.0.0 still same

**Comment by BornToBeRoot** [comment]
The WebView (Microsoft Edge) doesn't allow to connect to website with an untrusted certificate. But `http` should work.

https://github.com/BornToBeRoot/NETworkManager/issues/244#issuecomment-573379473

**Comment by abasitali** [comment]
=( it will not work for the server consoles or stuff like with untrusted certificates .......... It doest even give warning or something..

**Comment by RafalNiewinski** [comment]
I think there is a need to somehow solve this problem.
Most of management consoles (servers, routers, switches, etc.) are untrusted.

**Comment by BornToBeRoot** [comment]
The current webview (based on edge) doesn't allow to ignore ssl certificates.

WebView2 may does, because it is based on chromium, but the first preview of the control for .NET (WPF) will be available at march. Maybe it's released at the end of the year?!

The alternative is CefSharp (Chromium), but this will blow up the installation... Current zip-file is about ~7 MB, with CefSharp it's over 100 MB.

The second alternative would be using Internet Explorer as control... But who wants that 😄? 

This blog is also interesting:
https://www.suchan.cz/2015/10/displaying-https-page-with-invalid-certificate-in-uwp-webview/
https://www.suchan.cz/2016/11/hacking-uwp-webview-part-3-bypassing-https-certificate-validation-in-uwp-webview/

**Comment by BornToBeRoot** [comment]
1) Most https sites allow the certificate to be exchanged for your own (e.g. from an internal PKI). 

or

2) Import the untrusted certificate as trusted root ca. This is really dirty and i can't recommend it... This also makes only sense if you connect often to a specific https site...


Both options work...

**Comment by BornToBeRoot** [comment]
@abasitali @RafalNiewinski 

With WebView2 you can finally accept untrusted SSL certificates 😄 

![image](https://user-images.githubusercontent.com/16019165/91698683-6666c900-eb73-11ea-8d87-eb53372bd990.png)

I currently migrating to .NET 5.0 and will release a preview soon. The "issue" will fixed in the next release!

**Comment by BornToBeRoot** [comment]
Fix: https://github.com/BornToBeRoot/NETworkManager/releases/tag/2020.9.0
