### ISSUE TITLE
Add IP2Location.io IP Geolocation API

### ISSUE THREAD

**Issue by ip2location-com** [BornToBeRoot/NETworkManager#2807]
**Describe your feature request**:
I saw one of your pull requests mentioned the use of geolocation API. I would like to recommend the use of the IP2Location.io IP Geolocation API.

[https://www.ip2location.io/](https://www.ip2location.io/)

You've mentioned in the pull request that you would prefer not to use an API key.

The IP2Location.io API can be used without an API key for 500 IP address queries per day. If used with the [free API plan](https://www.ip2location.io/pricing) key, you can query up to 30,000 IPs per month.

**Comment by BornToBeRoot** [comment]
Hi @ip2location,

I have currently implemented ip-api.com which fulfils my requirements. As a separate tool and in e.g. traceroute.

https://borntoberoot.net/NETworkManager/docs/application/ip-geolocation
https://borntoberoot.net/NETworkManager/docs/application/traceroute

The free endpoint offers 45 requests per minute (~65k/day) and i/the user don't need an API key. I also do not have the option of saving an API key securely in the application. Otherwise, every user has to register themselves.

But your projects also looks nice. Are there any advantages with your api?
