### ISSUE TITLE
希望添加配置文件导入导出，及IP地址备注功能

### ISSUE THREAD

**Issue by xindong883** [BornToBeRoot/NETworkManager#2865]
**Describe your feature request**:
希望添加配置文件导入导出，及IP地址备注功能

**Comment by BornToBeRoot** [comment]
Hey @xindong883,

you can copy & paste the settings & config files as long as you have the same (or a newer) version of NETworkManager. The files are stored in the documents folder (and can sync via something like onedrive). See: https://borntoberoot.net/NETworkManager/docs/faq/file-locations#where-are-files-stored

The import/export was remove in a previous version due to multiple bugs. I will rework the function as part of #2679 & #2700

I will add a textbox to enter a description for a host/profile.

**Comment by BornToBeRoot** [comment]
Implemented in https://github.com/BornToBeRoot/NETworkManager/releases/tag/2024.11.11.0
