### ISSUE TITLE
Ping Monitor: UDP-Ping

### ISSUE THREAD

**Issue by chr15t0ph** [BornToBeRoot/NETworkManager#315]
First of all: Your tool is great! Big Thx!!

**Describe your feature request**:
I would like you to implement UDP-based Ping, for your Ping Monitor.

** Background **
I assume you implement standard ICMP-ping.
However, there are options to implement UPD- and TCP-based ping methods with IPv4, too.
As a reference, please refer to: https://www.netscantools.com/nstpro_ping.html

The UDP-ping variant with IPv4 would be most helpful to me. This is related to an analysis attempt of OpenVPN over UDP. I skip the details, but I would like to UPD-ping-monitor several hosts that are part of the VPN routing, but (!) I would like to ping them with their (Non-VPN) external IPs. I do not trust the ICMP-ping to provide the same monitoring characteristics (packet drop) compared to the UPD packets that the OpenVPN takes. All in all, I distrust my ISP provider, to either drop UDP packets more often than TCP packets or to cause an MTU-related problem that increases the UDP packet drop frequency.

**Comment by BornToBeRoot** [comment]
Hi, sorry for my late reply.

I dont know if this is possible without capturing network packages... The enhanced ping tool uses WinPcap (https://www.winpcap.org/) to listen for icoming icmp packages.

I don't want to install a network card driver with my software, because this would break the portable feature. It's also a lot of work, for this specific feature :)

Maybe you should take a look at nmap (https://nmap.org/). They support UDP ping.

Greetings.
