### ISSUE TITLE
TAP / OpenVPN connections are not visible

### ISSUE THREAD

**Issue by wolph** [BornToBeRoot/NETworkManager#375]
**Describe your issue**:

The list of interfaces doesn't show TAP / OpenVPN (and other VPN) client connections.

**Steps to reproduce the issue**:

1. Connect to a VPN
2. Try to find the information in the interfaces list

**NETworkManager version**: 2020.5.1

**Windows version**: Windows 10 v2004 (build 19041.546)

**.NET-Framework version**: Probably not relevant either way, where can I find out?

**Screenshots**
![image](https://user-images.githubusercontent.com/270571/99980532-a3281200-2da8-11eb-9b35-4707f590c99f.png)

**Comment by BornToBeRoot** [comment]
Are you sure? Maybe under a different name like "Ethernet XY"?

I have also use the OpenVPN adapter and i can see it in the list as Ethernet device.

![image](https://user-images.githubusercontent.com/16019165/100017355-0d59aa80-2ddb-11eb-9e70-6d19c03c335e.png)


![image](https://user-images.githubusercontent.com/16019165/100017394-1ba7c680-2ddb-11eb-93b7-84f9d94487cc.png)

![image](https://user-images.githubusercontent.com/16019165/100017758-b3a5b000-2ddb-11eb-8773-821c9a6401ba.png)

**Comment by wolph** [comment]
Yes I'm pretty sure. It seems there are actually 2 interfaces missing:
![image](https://user-images.githubusercontent.com/270571/100017973-fa93a580-2ddb-11eb-9a59-fb1192ac357f.png)

![image](https://user-images.githubusercontent.com/270571/100018267-7db4fb80-2ddc-11eb-9b70-5c5da406ef03.png)

**Comment by BornToBeRoot** [comment]
Interessting... the `NetworkInterfaceType` ist 53 for this adapters...

https://docs.microsoft.com/en-us/windows-hardware/drivers/network/ndis-interface-types
https://stackoverflow.com/questions/58821325/networkinterfacetype-53

Here is the "bug"/filter: https://github.com/BornToBeRoot/NETworkManager/blob/38a075acd8cfdd4e1ea9ebd38f6b327abf08ae02/Source/NETworkManager.Models/Network/NetworkInterface.cs#L37

I will add it for the next release! Thanks for reporting!

**Comment by wolph** [comment]
Excellent! Thank you for the quick fix :)

**Comment by wolph** [comment]
Out of curiosity, wouldn't duck typing be a better option in that bit of code? Accept all options but with a try/catch or attribute test instead? This code looks prone to breaking if someone thinks of a new `NetworkInterfaceType`

**Comment by BornToBeRoot** [comment]
The most common are `Ethernet` and `Wireless80211`. It seems like the Tap adapther is sometimes recognized as virtual/internal interface.

The problem is, when you allow everything, you might get interfaces like modem, isdn, etc.. This shouldn't be a problem if you only display the details, but i don't know what happen if you try to configure (static ip, dns) the interface from my tool or capture network packages (LLDP/CDP). And i don't have a device to test all these interface types.

According to the .net documentation, there are only a few interfaces:
https://docs.microsoft.com/en-us/dotnet/api/system.net.networkinformation.networkinterfacetype?view=net-5.0

if you look at other documentations from microsoft, there are a lot more interfaces defined:
https://docs.microsoft.com/en-us/windows-hardware/drivers/network/ndis-interface-types

For now i would add the type 53 in the if condition. This was also the first time (in 4 years) someone reported an issues, that an interface was missing.

**Comment by wolph** [comment]
Yes, that makes sense :)

As a fellow developer I'm always a bit scared when I see these types of special cases without any `else` as it can cause issues you'll never notice. In this case however... it prevents rare and hard to reproduce bugs so I guess it's the better of the two :)

**Comment by BornToBeRoot** [comment]
Hi,

can you run this build to get the NetworkInterfaceType. It should display a messagebox.

![image](https://user-images.githubusercontent.com/16019165/102000187-14425180-3ce5-11eb-83f5-2834faf48638.png)


The build is based on the last release, so you need .NET 5.0 Desktop to run it.

Download (via nextcloud, because it's too large for the comments ;( )

https://cloud.borntoberoot.net/s/fAHAqLPCe8twRLG
PW: `2020Issue#375`

**Comment by wolph** [comment]
I'm not able to download it unfortunately
![image](https://user-images.githubusercontent.com/270571/102000430-a0557880-3ce7-11eb-97c5-0443c8d357ed.png)

**Comment by BornToBeRoot** [comment]
LOL. Does work on my pc ^^

Did you enter the password and hit enter? Dont click on "Request password"

**Comment by wolph** [comment]
You're right. I absent-mindedly clicked on the button :P

It shows this messagebox 2 times:
![image](https://user-images.githubusercontent.com/270571/102014032-24dde080-3d54-11eb-9827-6a41434fe06d.png)
Followed by this one:
![image](https://user-images.githubusercontent.com/270571/102014037-40e18200-3d54-11eb-8071-88c4e14b6bd6.png)

**Comment by BornToBeRoot** [comment]
Great! In .NET the interfacetype 53 is not available as enum. 
So i was unsure if it is `int` 53 or `NetworkInterfaceType.Unkown`.

Here is the fix if you want to try it out and test if it works.


https://cloud.borntoberoot.net/s/6EXtsNtqmbzNR6Y
PW: `2020Issue#375`

PR: https://github.com/BornToBeRoot/NETworkManager/pull/394

It will be available in the next release!

**Comment by wolph** [comment]
Working great! Thank you :)

![image](https://user-images.githubusercontent.com/270571/102080647-1e606f00-3e0f-11eb-8c3f-7fad17ccd34d.png)
