### ISSUE TITLE
Shared Profiles between Ping, Traceroute, etc.

### ISSUE THREAD

**Issue by nittanygeek** [BornToBeRoot/NETworkManager#92]
I would love to switch to this from using mRemoteNG, but I'm having a difficult time in getting the profiles setup between Ping, Traceroute, RDP, etc.  I feel like the user should just be able to select the node once it's setup the first time instead of needing to re-enter it in every tab.  This is not good for networks on a large scale.

**Comment by BornToBeRoot** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/16019165/41511841-3793f478-727f-11e8-8834-2b5e75f6994f.png)

Where you can enable the profile for each tool and set advanced settings like Website/Port (Port scanner) or MAC-Address (Wake on LAN) ?! And you can also overwrite the hostname, because for the ip scanner maybe the whole subnet makes more sense....

![image](https://user-images.githubusercontent.com/16019165/41511843-3f2eb79a-727f-11e8-8b2c-540f03f425ca.png)

**Comment by BornToBeRoot** [comment]
The feature will be available in the next version!
